### PR TITLE
Add slides for M1 workshop

### PR DESCRIPTION
**Pull request by teodutu**
These are the slides for the presentation held at the Milestone 1 workshop. The event's description is added by https://github.com/open-education-hub/open-education-hub-site/pull/19.

### CODE REVIEW

**Comment by razvand** [comment]
@teodutu , please merge all commits into one and add `Signed-off-by` messages with all of us (@razvand , @lizababu , @RazvanN7 , @Sergiu121 ).

**Comment by teodutu** [comment]
@razvand done.

**Comment by razvand** [comment]
@VladNastase , @Sergiu121 , how could we have the slides here render on the [website](https://open-education-hub.github.io/docs/events/m1)?

**Review by razvand — APPROVED** [review]
Looks good.

**Pull request merged**
