### PR TITLE
community: Add bios for Hulda and Eggert

### PR DESCRIPTION
**Pull request by eggertkarl**
Created with RazvanN's help.

### CODE REVIEW

**Review by razvand — CHANGES_REQUESTED** [review]
Please rebase the PR to only have a commit on top of `main`.

Resize your image to about 200-250 size. See the syntax [here](https://raw.githubusercontent.com/open-education-hub/open-education-hub-site/main/website/docs/community/people.md).

**Comment by eggertkarl** [comment]
Is this better?

**Comment by razvand** [comment]
@eggertkarl , it's perfect, thanks! Will integrate.

**Review by razvand — APPROVED** [review]
This is great. Thanks, @eggertkarl , @huldahvonn .

**Pull request merged**
